sudo: required
language: python
# Keep up to date with the tox.ini list
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libraw-bin

install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - make docs
  - make test
after_success:
  - coveralls
