sudo: false
language: python
# Keep up to date with the tox.ini list
env:
  - TOXENV=py27
  - TOXENV=py36
  - TOXENV=pypy
addons:
  apt:
    packages:
      - libraw-bin
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - make docs
  - make test
after_success:
  - coveralls
